### PR TITLE
Ot/galdera: fix some character names

### PR DESCRIPTION
**Pull request by aspiwack**
Does it matter? Not at all. Am I in this kind of mood? Apparently.

### CODE REVIEW

**Review by ak505188 — COMMENTED** [review]
Gonna deny this one for CTRL-F style reasons

**Comment by aspiwack** [comment]
I can type Hróðvitnir with my keyboard (compose+'+o and compose+d+h, respectively), but I'll gladly admit that using the compose key for accurate diacritics is a pretty niche hobby.

H'aanit is spelt inconsistently one way or the other throughout, maybe at least we ought to choose which, and I can make the corresponding change.

**Comment by ak505188** [comment]
Yeah, I'm cool with changing H'aanit to either spelling for consistency. You can pick which spelling you'd like. If it's not too much trouble, can you change it in all the other notes as well? Should be only the full game categories.

**Comment by aspiwack** [comment]
Done :slightly_smiling_face: 

By the power of

```sh
$ find -iname "*\.mdx" | xargs sed -i "s/Haanit/H'aanit/g"
```

(I'm not 100% sure why it fails on some file names, but I don't need to change the spelling of H'aanit in Suikoden routes, so whatever)

I chose the pedantic spelling. But it also seems that it was the most common spelling throughout the notes by a pretty large margin.

**Pull request merged**
